# Generated by Django 6.0.2 on 2026-02-13 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_main', models.URLField(help_text='Main hotel image')),
                ('image_room', models.URLField(help_text='Room view image')),
                ('map_3d_url', models.URLField(help_text='Google Maps 3D Embed Link')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('passengers', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI/Paytm'), ('CARD', 'Credit/Debit Card'), ('BANK', 'Net Banking')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('stars', models.IntegerField(default=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.hotel')),
            ],
        ),
    ]
