# Generated by Django 6.0.2 on 2026-02-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='total_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='travel_mode',
            field=models.CharField(default='airplane', max_length=50),
        ),
    ]
