# Generated by Django 6.0.2 on 2026-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticketbooking_total_price_ticketbooking_travel_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_main',
            field=models.ImageField(help_text='Main hotel image', upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_room',
            field=models.ImageField(help_text='Room view image', upload_to='hotels/rooms/'),
        ),
    ]
