# Generated by Django 6.0.2 on 2026-02-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hotel_image_main_alter_hotel_image_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_main',
            field=models.ImageField(blank=True, help_text='Main hotel image', null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_room',
            field=models.ImageField(blank=True, help_text='Room view image', null=True, upload_to='hotels/rooms/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='map_3d_url',
            field=models.URLField(help_text='Google Maps 3D Embed Link', max_length=500),
        ),
    ]
