# Generated by Django 6.0.2 on 2026-02-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hotel_image_main_alter_hotel_image_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('leisure', 'Leisure'), ('business', 'Business'), ('honeymoon', 'Honeymoon'), ('family', 'Family')], default='leisure', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=5000, help_text='Price per night in ₹'),
        ),
    ]
